### ISSUE TITLE
Gender-specific form sprites aren't shown properly on battle pages

### ISSUE THREAD

**Issue by adhameer** [Zhorken/tcod-asb#97]
On the main page for a battle, Pokémon don't have gender-specific icons at all (e.g. Frillish sprites show the default female sprite regardless of gender). On the approve battle page, you get icons like /static/images/pokemon-icons/frillish-&lt;asb.db.tables.Gender object at 0x7f94f2b8d320&gt;.png.

**Comment by Zhorken** [comment]
Gender object at 0x7f94f2b8d320 is the best gender, what are you talking about

**Comment by adhameer** [comment]
Then, clearly, it should be associated with a proper PNG!
